### ISSUE TITLE
The captions of "DPQuery_Tool.exe" are not appropriate.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#109]
# The explanation of the item should be a noun.
- "I want the data provider" -> "Data Provider"
- "I set the connection string" -> "Connection String"
- "I choose the slot" -> "Slot"
- "I want the interface" -> "Interface"

In the first place, I don't want the data provider. I want to choose the data provider.

# The caption of button should be a imperative form.
- "Creating configuration" -> "Create configuration"
- "Connection" -> "Connect"
- "Query execution" -> "Execute query"

# A wrong word is used.
- "Cutting" -> "Disconnect"

# The word of similar meaning is mixed.
"Setting"?"Configuration"?

# The request for improvement.
I cannot change the name of slot.
Because of that, I must remember how I set each slot.
Therefore, I want to change the name of slot.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

The above analysis are correct as per the English language.

There must be following modifications required in the "DPQuery_Tool.exe".
- Captions must be noun instead of sentences.
- There may be change required in the error messages and information messages used in this tool, to improve the meaning of those messages.
- UI improvement of the tool, to make better look-and-feel, it will make your promoting video more attractive.

We will propose modified "DPQuery_Tool” and send you the screen shots.
Shall we do the above modification to improve the "DPQuery_Tool”?

Please confirm.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

>We will propose modified "DPQuery_Tool” and send you the screen shots.
Shall we do the above modification to improve the "DPQuery_Tool”?

Yes, please.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Thank you for the confirmation.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Does this Issue have been completed　?

**Comment by SandeepNayak077** [comment]
@daisukenishino 

\>> Does this Issue have been completed　?

Yes, it is completed.
We are waiting for your approval to do code commit in the "OpenTouryo".

Please let us know.

**Comment by daisukenishino** [comment]
Please send the pullrequest to [OpenTouryoProject/OpenTouryou](https://github.com/OpenTouryoProject/OpenTouryo).

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.
We will commit the canges in new feature branch,
and create pull request to OpenTouryoProject/OpenTouryou's develop branch.

**Comment by daisukenishino** [comment]
It was fixed by the following PR.
https://github.com/OpenTouryoProject/OpenTouryo/pull/126
