### ISSUE TITLE
Please correct the unnecessary "if" to "else if". Because the decision process in the DPQuery_Tool is increased.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#125]
# Requirement

Please correct the unnecessary "if" to "else if".
Because the decision process in the DPQuery_Tool is increased.

- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form1.cs#L590
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form1.cs#L610
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form1.cs#L631

#### as-is
```C#
if (this.cmbDataProvider.SelectedItem.ToString() == Literal.DAP_XXX)
```

#### to-be
```C#
else if (this.cmbDataProvider.SelectedItem.ToString() == Literal.DAP_XXX)
```

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Since there are too many "if-else",
Shall we change to "switch" statement instead of "if-else"

Please confirm

**Comment by daisukenishino** [comment]
@SandeepNayak077 

We would like to fix if there is big performance improvement.

I tried to research by consuming a short time.

- c# - Is else if faster than switch() case - Stack Overflow  
http://stackoverflow.com/questions/767821/is-else-if-faster-than-switch-case

However, I think that the actual performance difference is not know if you do not try to actual measurement. And, If it is slight improvement, I do not want to fix it.

Therefore, we will agree to do the modification, if possible proof that there is a big difference in performance, but we believe that there is no need to spend time to investigation if it is not known at the moment.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the reply.

Yes, there will be slight improve in the performance.
To check for big improve in the performance, it requires to investigate overall code.

Because we are working with high priority merge task.
So, we request you to close this task.
In future, when we find the big performance difference, we will request to create new issue.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

As per the links
http://programmers.stackexchange.com/questions/15820/should-i-use-switch-statements-or-long-if-else-chains
http://stackoverflow.com/questions/767821/is-else-if-faster-than-switch-case

It is better option of changing to switch instead of if..else as per the performance consideration.

We will change it to Switch and send the pull request.

Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Benefits as performance improvement of the UI processing is small that compared with the batch processing. And, [this modifications is difficult to check the difference compared to the elseif modification](https://github.com/SymphonyTeleca/OpenTouryo/pull/86/files). therefore, reviews are difficult.

If sending the evidence that is tested all of the coverage has been completed, then accept this pull request. please send the evidence. However, it should be taken into consideration that takes time and effort to each other.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>If sending the evidence that is tested all of the coverage has been completed, then accept this pull request. 

We have tested with SQLServer database by debugging code of Switch case, it is working fine.

We also created evidence for the above test.

We uploade the files in IPServer.
Location is:[/V-RW/PJ2/IfelseEvidence]
