### ISSUE TITLE
Changing the resource file name ( ja-jp ---> ja ).

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#167]
# Requirement

- If the **"jp"** resource files does not exist.
- And, if the **"ja-jp"** resource file exist.
- Then, if the UI culture is **"jp"**.

In this case, It will used default resource file (**"en"**) of parent culture rather than **"ja-jp"** resource file by fallback feature. This is a problem, we think that it is necessary to change the resource file name from **"jp-jp"** to **"jp"**.

### see
- カルチャ - マイクロソフト系技術情報 Wiki - 概要 - 構造  
https://techinfoofmicrosofttech.osscons.jp/index.php?%E3%82%AB%E3%83%AB%E3%83%81%E3%83%A3#jd411d68

##### resource file
- MyBusinessApplicationExceptionMessageResource.ja-JP.resx  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.ja-JP.resx
- MyBusinessSystemExceptionMessageResource.ja-JP.resx  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessSystemExceptionMessageResource.ja-JP.resx

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Do you have any trouble with "ja-jp"?
Please describe the details of this issue.
Others can not understand what is the issue.

**Comment by daisukenishino** [comment]
# ・・・

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-205643248

This tool has a mechanism of culture settings.

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/app.config#L211
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Program.cs#L63

But the default resource file ("en") has not been applied in the setting of "ja" by fallback feature.
Therefore, currently, additional research is required.

**Comment by supragyan** [comment]
@daisukenishino 

The following tools has been tested by different culture settings.

 - DPQuery_Tool
 - DaoGen_Tool
 - DeployZipPackWithHTTP
 - Workflow_Tool

## Different Culture Settings 
### ja-JP
Change the settings as the following 
```CS
<add key="DefaultCulture" value="ja-JP"/>
```
### ja
Change the settings as the following 
```CS
<add key="DefaultCulture" value="ja"/>
```
**Result**
By these two culture settings(ja-JP,ja) the tools are displaying in Japanese language.
Because ja-JP resource file is available in all tools.

### en_us
Change the settings as the following 
```CS
<add key="DefaultCulture" value="en-US"/>
```
**Result**

By this culture setting(en_us) the tools are displaying in English language.
Because en resource file is available.

### zh-CN
Change the settings as the following 
```CS
<add key="DefaultCulture" value="zh-CN"/>
```
**Result**
By this culture setting(zh-CN) the tools are displaying in English language.
Because the zh-CN culture is identified by .Net but the resource file is not available in our Tools.
So it will redirect to default language i.e English.

### Issues Identified

### en-xyz
Change the settings as the following 
```CS
<add key="DefaultCulture" value="en-xyz"/>
```
**Result**
But this en-xyz resource file does not exist but still its redirecting to English language.

Similarly 
### ja-xxx
Change the settings as the following 
```CS
<add key="DefaultCulture" value=" ja-xxx"/>
```
**Result**
ja-xxx resource file does not exist but still its redirecting to Japanese language.
Because its taking first two digit of characters of DefaultCulture value and redirects to that language resource file if it exist.

Do we need to restrict that?

### Solution
We need to have one collection which will contain language codes of Japanese(ja,ja-JP) and English(en).
Tool will search the existence of language codes in collection.
If that language exist then it will set the culture accordingly or else it will set to default language i.e English(en).

Please suggest your opinion.

**Comment by daisukenishino** [comment]
@supragyan 

Thank you survey.

the following survey result was very helpful.

>**ja-xxx** resource file does not exist but still its redirecting to Japanese language. Because its taking first two digit of characters of DefaultCulture value and redirects to that language resource file if it exist.

However, the proposed of solution is not appropriate.


If the above specifications of survey result is included in the fallback feature, then I think that this correspondence is unnecessary. So I will close this issue.
