### ISSUE TITLE
"progress dialog display" function does not work on the Updatepanel.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#175]
# Requirement
- If Ajax and POST are mixed
- Setting status, such as UpdateMode and ChildrenAsTriggers
  - UpdatePanelについて - 潜在推力  
http://d.hatena.ne.jp/ps1/20081101/p1

There is a report that behavior is changed by the above-mentioned.

### Add the test cases and perform test.
Please add the test cases to the following screens and perform test.

- **ProjectX_sample/Aspx/testFxLayerP/withAjax/**
  - testExtension_Single.aspx
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/withAjax/testExtension_Single.aspx
  - testExtension_Separate.aspx
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/withAjax/testExtension_Separate.aspx

**Comment by daisukenishino** [comment]
@SandeepNayak077 

If you use the UpdatePanel, there is a case in which dialog is not displayed. This is due to the implementation conditions of the program. I think that there is highly possibility that phenomenon is related to the condition of "mode" and "trigger". If the program is consistent with the implementation conditions, this phenomenon is reproduced 100%.

Please investigate this condition.
In addition, you should consider the countermeasures.

**Comment by SandeepNayak077** [comment]
@daisukenishino

<h3>Test report</h3>

We have tested for the following permutation and combination of implementation conditions:
- UpdateMode: "Always" (Default) or "Conditional"
- Control outside UpdatePanel: Registered as "AsyncPostBackTrigger" or "PostBackTrigger"
- Control inside UpdatePanel: Registered as "AsyncPostBackTrigger" (Default) or "PostBackTrigger"
- ChildrenAsTriggers (When, UpdateMode="Conditional"): "true" (Default) or "false"
 
For all test conditions, progress dialog was displaying only after 2 seconds, because of [this timer condition](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L406).

<b>Additional tests:</b> 
We have also tested for nested UpdatePanel and multiple UpdatePanel with the above permutation and combination of implementation conditions.
We have also tested GridView inside UpdatePanel by using [testGridView](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/table/testGridView.aspx) and [ProductsConditionalSearch](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsConditionalSearch.aspx)
For all test conditions, progress dialog was displaying after 2 seconds processing time. 

We have tested using current latest OT/develop branch, having latest common.js file.

Since we are not able to reproduce this issue in our environment.
We are requesting to give the implementation condition of user, which is reproducing this issue.

Please let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

We do not even know the clear conditions.
If this problem does not occur by your investigation in today,
then I will stop once this investigation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/175#issuecomment-218630025

Thank you for confirmation.
We will stop investigation on this task for time being and start working on https://github.com/OpenTouryoProject/OpenTouryo/issues/174 task.

Please let us know if you come across the possible scenario to reproduce this issue.
