### ISSUE TITLE
Feature Request: Add support for ODP.NET Managed Driver

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#229]
# Requirement
Currently, open touryo uses [odp.net.x86](https://www.nuget.org/packages/odp.net.x86/) NuGet package. This package requires Oracle Client. So developers should install Oracle Client on execution machines.

Oracle provides [ODP.NET Managed Driver](https://www.nuget.org/packages/Oracle.ManagedDataAccess/) in Oracle 12c. ODP.NET Managed Driver is written all in managed code, and does not require Oracle Client. So constructing a environment will get easier. Furthermore, coding style is mostly unchanged.

According to [this page](http://www.oracle.com/technetwork/topics/dotnet/install121024-2704210.html), ODP.NET in ODAC 12c can access to an Oracle database 10g or later. 

I think ODP.NET Managed Driver is useful when using Oracle database.
Could you consider adding support for ODP.NET Managed Driver?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I agree.

### Planning
CRUD test and automatic generation test are required.

#### Release time
Since there are many tests.
This release will be scheduled for the next term (from April 2017 to September 2017).

#### Considerations
We will adopt a method to ask the project to test during the project.
For this reason, we will leave DamOraOdp so that we can revert when problems occur.
- Exclude DamOraOdp from the solutions.
- DamOraOdp will be only excluded, not be deleted.
- And, add the new Dam of DamMgrOdp.
- Grep and replace the existing code as follows by Sakura Editor.
  - Replace Oracle.DataAccess with Oracle.ManagedDataAccess.
  - Replace DamOraOdp with DamMgrOdp.

### Reference
- 素敵なおひげですね
  - Oracle Client(ODP.NET)を手っ取り早くインストールする方法について
http://stknohg.hatenablog.jp/entry/2014/10/24/074303
  - ODP.NET Managed Driver(管理対象ドライバ)についての私的まとめ  
http://stknohg.hatenablog.jp/entry/2014/11/02/173039
- Oracle Help Center
  - Oracle Data Provider for .NETのアセンブリ  
Oracle Data Provider for .NET管理対象ドライバ・アセンブリ  
http://docs.oracle.com/cd/E57425_01/121/ODPNT/intro003.htm#BHCFHCAF
  - ODP.NET管理対象ドライバと管理対象外ドライバの相違点  
http://docs.oracle.com/cd/E57425_01/121/ODPNT/intro004.htm#CEGEJIFD

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> - And, add the new Dam that is named DamMgrOdp.

I think that *Mgr* is an abbreviation for *Manager*. (not *Managed*)
So, I think that new data access manager should be named *DamManagedOdp* or *DamOdpManaged*.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I adopt DamManagedOdp.
