### ISSUE TITLE
Support the.NET Standard2.0 and .NET Core2.0 .

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#235]
# Requirement
In the future, to support such as .NET Core, I try to separate the classes that operate on ".NET Standard" in the "Public" namespace into the "Standard" namespace.

- Migrate library of Public namespace to Standard namespace.
- Change it to use the library migrated from the Public namespace to the Standard namespace.

**Comment by daisukenishino2** [comment]
There are some trajectory corrections, but we started verification.

- .NETのクロスプラットフォーム対応 - マイクロソフト系技術情報 Wiki
https://techinfoofmicrosofttech.osscons.jp/index.php?.NETのクロスプラットフォーム対応
  - [.NET Standardへの移行](https://techinfoofmicrosofttech.osscons.jp/index.php?.NET%20Standard%E3%81%B8%E3%81%AE%E7%A7%BB%E8%A1%8C)
  - [.NET Coreへの移行](https://techinfoofmicrosofttech.osscons.jp/index.php?.NET%20Core%E3%81%B8%E3%81%AE%E7%A7%BB%E8%A1%8C)
  - [ASP.NET Coreへの移行](https://techinfoofmicrosofttech.osscons.jp/index.php?ASP.NET%20Core%E3%81%B8%E3%81%AE%E7%A7%BB%E8%A1%8C)

By proceeding with the verification it will be closer to the final answer.

**Comment by daisukenishino2** [comment]
Currently, It have completed migration of Public namespace and Framework namespace. Though the #IF-DEF directive was used in the work, the code base is in the nearly equal state and we think that netstandard assembly can be generate by build without duplicating the source code.

Obtain the following diff if confirm.

- Source
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure
- Destination
https://github.com/OpenTouryoProject/SampleProgram/tree/netstandard/PrototypeModel/NETStandard

As a result, this netstandard assembly can added to the same NuGet package as target="lib\netstandard".

And there is a attention matter that the features provided by the netstandard assembly is a subset of net assembly, it can not provide complete functions to net program. Therefore net program will continue to use the net assembly instead of netstandard assembly. On the other hand, netcore and mono program use netstandard assembly. But fortunately, this behavior is the default UX when using the NuGet package created in the above procedure.

In addition, since the Business namespace is a customizable layer, I think that it should be implemented with netstandard and mono instead of netstandard. And, whether the libraries of netcore and mono should supplement missing functions, location of the supplementary layers should be considered at beforehand.

**Comment by daisukenishino2** [comment]
### Considerations related the test
Perform the test from the netcore repository.
