### ISSUE TITLE
Do not stop the submission even if can not determine the browser.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryo#304]
# Requirement
https://groups.google.com/forum/?hl=ja#!topic/opentouryoproject/P8Q_z0WTql4

**Comment by daisukenishino** [comment]
# Additional information
Looking inside Fx_OnSubmit() function at the latest version of Chrome (71),
"Browser_IsChrome" flag was false.

- Screen sharing not working in Chrome 71 · Issue #1350 · nextcloud/spreed
https://github.com/nextcloud/spreed/issues/1350

Although it is Fx_OnSubmit () function, since submit processing originally performed fuzzy on IE and Edge, it was controlled by readyState. The next HTTP post request is possible even if IE and Edge has not receive the HTTP response completely.

However, I think that other modern browsers are basically implemented so as not to transmit twice, so nowadays, I think that there are few people paying attention to duplex transmission to the general public in general.

In that sense, it seems to be good to put "return true;" as the default value below.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/CS/Samples/WebApp_sample/WebForms_Sample/WebForms_Sample/Scripts/touryo/common.js#L317

**Comment by daisukenishino** [comment]
### Will be corresponds as follows.
Implement the following code to the following location.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/CS/Samples/WebApp_sample/WebForms_Sample/WebForms_Sample/Scripts/touryo/common.js#L317

```JS
    else {
        // その他のブラウザ
        // ・・・
        if (Form_IsSubmitted) {

            // A postback or an Ajax request is processing
            // Prevent other transmissions
            return false;
        }
        else {

            // 送信許可
            Fx_SetProgressDialog();

            // Set double submission prevention flag
            Form_IsSubmitted = true;
            return true;
        }
    }
```
