### ISSUE TITLE
strange warning about CS1685

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#62]
The following warning is output at the time of build.
Please investigate the cause of this warning and resolve.

warning CS1685 : The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'c:\Progr
am Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core
.dll'

**Comment by kishoreandukuri** [comment]
HODC has fixed the issue of showing warning ‘CS1685’ while building batch file ‘7_Build_Framework_WS.bat’.

By removing dlls ‘System.core’ and ‘Newtonsoft.Json.dll’ in the path of bin directory ‘root\programs\C#\Frameworks\Infrastructure\ServiceInterface\ASPNETWebService\Bin’.

Please refer the link for more information ‘http://stackoverflow.com/questions/546819/strange-warning-about-extensionattribute’.

HODC has not done any code commit since this change is made in bin folder.

This bin folder is not present in GitHub for commit.

Please let us know.

**Comment by daisukenishino** [comment]
In other words,
  There is no problem. It is mere warning.
    Therefor, don't need to correct this problem.
I understood as described above.
